# Generated by Django 3.2.6 on 2021-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeinfo',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='login_datetime',
            new_name='login_time',
        ),
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='logout_datetime',
            new_name='logout_time',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='minutes',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='attendance_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='login_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='logout_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='employeeaccount',
            table='employee_account',
        ),
        migrations.AlterModelTable(
            name='employeeinfo',
            table='employee_info',
        ),
    ]
