# Generated by Django 3.2.7 on 2021-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210915_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='workhour_set',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='attendance_status',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
