# Generated by Django 3.2.7 on 2021-09-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210917_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeaccount',
            old_name='user_name',
            new_name='username',
        ),
    ]
