# Generated by Django 3.2.7 on 2021-09-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_name_employeeaccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='workhour_set',
        ),
    ]
